.TH cw1-6005-ap20g11 1 "February 21, 2012" "version 1.0" "User Commands"
.SH NAME
6005_cw1_2012 \- the Simple PHP RSS Reader for INFO6005
.SH APPLICATION NAME
.B cw1-6005-ap20g11
.SH DESCRIPTION
This is part of a coursework for Students on the INFO6005 course at the University of Southampton.
In this course students are expected to package some code for distribution on the debian/ubuntu platform
.SH OPTIONS
.TP
get_news
display 10 items from feeds
.SH AUTHORS
6005_cw1_2012 - the Simple PHP RSS Reader for INFO6005 was implemented by University of Southampton, Electronics and Computer Science and was published: 30th Jan 2012. The package was created by <Popovidis Antonis>.
.PP
This manual page was written by Popovidis Antonis <ap20g11@soton.ac.uk>,
for the Debian project (and may be used by others).
